In [2]:
import numpy as np
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [5]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [9]:
np.random.rand(2,4)#0 to 1

array([[0.13504423, 0.28104325, 0.07378176, 0.67148047],
       [0.49545511, 0.51755716, 0.26684508, 0.92544202]])

In [10]:
np.random.randn(2,4)#normal

array([[-1.38172719, -0.81408492,  0.46612033,  0.89902884],
       [ 1.51249127, -0.38258576, -1.04181171, -0.07818485]])

In [11]:
np.random.randint(0,10,15)#no. from 0 to 9 and total no. should be 15(size)

array([7, 1, 1, 7, 8, 7, 6, 7, 4, 3, 4, 9, 5, 6, 0])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
l=[1,2,3]
np.array(l)

array([1, 2, 3])

In [14]:
m=np.array(l)
m

array([1, 2, 3])

In [15]:
lol=[1,2,3],[4,5,6],[7,8,9]#list of list
np.array(lol)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(10,34)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33])

In [17]:
np.arange(10,91,8)

array([10, 18, 26, 34, 42, 50, 58, 66, 74, 82, 90])

In [18]:
n=np.arange(2,20)
n

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [19]:
n.argmax()

17

In [22]:
n.dtype

dtype('int32')

In [25]:
n=n.reshape(6,3)
n

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [26]:
n.argmin()

0

In [27]:
n.argmax()

17

In [28]:
n[2:10]

array([[ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [31]:
n[2:4]=100
n

array([[  2,   3,   4],
       [  5,   6,   7],
       [100, 100, 100],
       [100, 100, 100],
       [ 14,  15,  16],
       [ 17,  18,  19]])

In [32]:
w=np.random.randint(0,10,5)
w

array([6, 5, 6, 9, 5])

In [33]:
w.min()

5

In [34]:
w.max()

9

In [35]:
w.argmax()

3

In [36]:
w.argmin()

1

In [38]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
a=np.random.rand(2,3)
a

array([[0.28584974, 0.26891617, 0.44813092],
       [0.61049048, 0.9257955 , 0.47993265]])

In [42]:
a.T

array([[0.28584974, 0.61049048],
       [0.26891617, 0.9257955 ],
       [0.44813092, 0.47993265]])

In [ ]:
#: stands for rows

In [44]:
sm=np.array([[24,13,2,15],[15,2,54,65],[56,76,24,7]])
sm

array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [45]:
sm[1:,2:]

array([[54, 65],
       [24,  7]])

In [46]:
np.square(sm)

array([[ 576,  169,    4,  225],
       [ 225,    4, 2916, 4225],
       [3136, 5776,  576,   49]], dtype=int32)

In [47]:
np.exp(sm)

array([[2.64891221e+10, 4.42413392e+05, 7.38905610e+00, 3.26901737e+06],
       [3.26901737e+06, 7.38905610e+00, 2.83075330e+23, 1.69488924e+28],
       [2.09165950e+24, 1.01480039e+33, 2.64891221e+10, 1.09663316e+03]])

In [48]:
np.mean(sm)

29.416666666666668

In [49]:
np.round(sm,decimals=3)

array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [51]:
sm[:,3]

array([15, 65,  7])

In [52]:
sm[1:3,2:4]

array([[54, 65],
       [24,  7]])

In [53]:
sm[2,2]

24

In [54]:
sp=np.arange(1,31)
sp

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [55]:
np.log(sp)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [56]:
np.std(sp)

8.65544144839919

In [57]:
np.sqrt(sp)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [58]:
np.var(sp)

74.91666666666667

In [59]:
ar=np.random.randn(3,4)
ar

array([[-0.32946272,  0.20250579, -1.2040371 ,  1.04249363],
       [ 0.55670113,  2.21064383, -0.04328289, -0.0400974 ],
       [ 0.78329806,  2.15857255,  0.39944815,  1.0118224 ]])

In [61]:
np.round(ar,decimals=3)

array([[-0.329,  0.203, -1.204,  1.042],
       [ 0.557,  2.211, -0.043, -0.04 ],
       [ 0.783,  2.159,  0.399,  1.012]])

In [62]:
f=np.array(['a','o','b','a'])
np.unique(f)

array(['a', 'b', 'o'], dtype='<U1')

In [63]:
import pandas as pd

In [64]:
s1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
s1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [65]:
s1['basketball']

3

In [66]:
s2=pd.Series([11,13,12,4],index=['cricket','football','basketball','golf'])
s2

cricket       11
football      13
basketball    12
golf           4
dtype: int64

In [67]:
s1+s2

cricket       12
football      15
basketball    15
golf           8
dtype: int64

In [80]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='S1 S2 S3 S4 S5'.split())

In [81]:
df1[['S2','S3','S4']]

S2        S3        S4
A  0.435601  0.366217  0.088628
B  0.055064  0.905654  0.317864
C  0.793234  0.604505  0.110979
D  0.444745  0.027324  0.256862
E  0.602209  0.731437  0.897979
F  0.524678  0.589033  0.011166
G  0.191241  0.316504  0.354434
H  0.421656  0.245015  0.408842

In [82]:
df1['S2']

A    0.435601
B    0.055064
C    0.793234
D    0.444745
E    0.602209
F    0.524678
G    0.191241
H    0.421656
Name: S2, dtype: float64

In [84]:
df1['S6']=df1['S1']+df1['S2']
df1

S1        S2        S3        S4        S5        S6
A  0.412847  0.435601  0.366217  0.088628  0.222764  0.848447
B  0.266975  0.055064  0.905654  0.317864  0.359079  0.322040
C  0.391624  0.793234  0.604505  0.110979  0.222487  1.184858
D  0.361286  0.444745  0.027324  0.256862  0.314438  0.806031
E  0.533231  0.602209  0.731437  0.897979  0.771627  1.135439
F  0.649547  0.524678  0.589033  0.011166  0.915994  1.174226
G  0.347125  0.191241  0.316504  0.354434  0.248917  0.538366
H  0.884964  0.421656  0.245015  0.408842  0.416265  1.306619

In [85]:
df1.drop('E')

S1        S2        S3        S4        S5        S6
A  0.412847  0.435601  0.366217  0.088628  0.222764  0.848447
B  0.266975  0.055064  0.905654  0.317864  0.359079  0.322040
C  0.391624  0.793234  0.604505  0.110979  0.222487  1.184858
D  0.361286  0.444745  0.027324  0.256862  0.314438  0.806031
F  0.649547  0.524678  0.589033  0.011166  0.915994  1.174226
G  0.347125  0.191241  0.316504  0.354434  0.248917  0.538366
H  0.884964  0.421656  0.245015  0.408842  0.416265  1.306619

In [86]:
df1.drop('S1',axis=1)

S2        S3        S4        S5        S6
A  0.435601  0.366217  0.088628  0.222764  0.848447
B  0.055064  0.905654  0.317864  0.359079  0.322040
C  0.793234  0.604505  0.110979  0.222487  1.184858
D  0.444745  0.027324  0.256862  0.314438  0.806031
E  0.602209  0.731437  0.897979  0.771627  1.135439
F  0.524678  0.589033  0.011166  0.915994  1.174226
G  0.191241  0.316504  0.354434  0.248917  0.538366
H  0.421656  0.245015  0.408842  0.416265  1.306619

In [87]:
df1.drop("A",axis=0)

S1        S2        S3        S4        S5        S6
B  0.266975  0.055064  0.905654  0.317864  0.359079  0.322040
C  0.391624  0.793234  0.604505  0.110979  0.222487  1.184858
D  0.361286  0.444745  0.027324  0.256862  0.314438  0.806031
E  0.533231  0.602209  0.731437  0.897979  0.771627  1.135439
F  0.649547  0.524678  0.589033  0.011166  0.915994  1.174226
G  0.347125  0.191241  0.316504  0.354434  0.248917  0.538366
H  0.884964  0.421656  0.245015  0.408842  0.416265  1.306619

In [88]:
df1.drop(["S1","S2"],axis=1)

S3        S4        S5        S6
A  0.366217  0.088628  0.222764  0.848447
B  0.905654  0.317864  0.359079  0.322040
C  0.604505  0.110979  0.222487  1.184858
D  0.027324  0.256862  0.314438  0.806031
E  0.731437  0.897979  0.771627  1.135439
F  0.589033  0.011166  0.915994  1.174226
G  0.316504  0.354434  0.248917  0.538366
H  0.245015  0.408842  0.416265  1.306619

In [70]:
df2={'ID':[101,102,103,107,176],'Name':['John','Merru','asd','safg','fdgg'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Merru      54
2  103    asd      56
3  107   safg      87
4  176   fdgg     123

In [89]:
df.drop('ID',axis=1)

Name  Profit
0   John      20
1  Merru      54
2    asd      56
3   safg      87
4   fdgg     123

In [90]:
df.drop(3)

ID   Name  Profit
0  101   John      20
1  102  Merru      54
2  103    asd      56
4  176   fdgg     123

In [91]:
df['Name']

0     John
1    Merru
2      asd
3     safg
4     fdgg
Name: Name, dtype: object

In [92]:
df[['Name','ID']]

Name   ID
0   John  101
1  Merru  102
2    asd  103
3   safg  107
4   fdgg  176

In [ ]:
df=pd.read_csv("innercity.csv")

In [93]:
df.head()

ID   Name  Profit
0  101   John      20
1  102  Merru      54
2  103    asd      56
3  107   safg      87
4  176   fdgg     123

In [74]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [75]:
a=np.zeros(10,int)
a[4]=1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [76]:
a=np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])